# path to root directory
save_dir: /workspace/open_unlearning/
repo_dir: .

# path to data directory
data_dir: ${paths.repo_dir}/data/

# path to dataset configs
datasets: ${paths.repo_dir}/configs/data/datasets

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics


output_dir: ${paths.save_dir}/saves/${mode}/${task_name}

# path to working directory
work_dir: ${hydra:runtime.cwd}