defaults:
  - _self_
  - model: gemma-2-2b
  - trainer: distill
  - data: finetune
  - collator: DataCollatorForSupervisedDataset
  - eval: tofu
  - hydra: default
  - paths: default
  - experiment: null

mode: train # Doesn't split data
task_name: ???