defaults:
  - _self_
  - model: gemma-2-2b
  - trainer: relearn
  - data: finetune
  - collator: DataCollatorForSupervisedDataset
  - eval: tofu
  - hydra: default
  - paths: default
  - experiment: null

mode: train
task_name: ???