defaults:
  - _self_
  - model: gemma-2-2b # student model
  - trainer: distill
  - data: finetune # NOTE: use same data as for finetuning? 
  - collator: DataCollatorForSupervisedDataset
  - eval: tofu
  - hydra: default
  - paths: default
  - experiment: null

mode: train
task_name: ???